[Build] Fixed Jetty problems
* Upgrade to Jetty 9.2.13 in order to fix NoClassDefFoundError
  occurring on shutdown via the Maven stop goal
  (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=438500)

Change-Id: Id72c0624531df0cfaf934877935c962b66a22466