[Java] Fixed NoSuchMethodError caused by joynr ObjectMapper
* Fixed NoSuchMethodError in shared subscription test where
  getPolymorphicTypeValidator() was not found